### PR TITLE
Logging helpers

### LINKED ISSUE #22: Logging
A consistent logging experience, and helpers to support that, seems like a good goal (and a good fit for this repo :+1:). The way I see it:
  1) The default Django logging configuration will likely never be sufficient for our production needs, so some sensible defaults (and a good API for extending those defaults) would be helpful. Something infrastructure-agnostic should be achievable
  2) Some patterns like audit trail logs should be consistent across projects, baking these in to the default configuration and providing some helpers for wiring the logging in to our apps will help drive that consistency. For example:
    - the discussion around audit log approaches in https://github.com/PHACDataHub/data-collection/pull/539
  3) Lastly, there's lots of opportunity to get better logs through custom handlers. For example:
      - integrating with/providing structured (JSON) logging output (https://github.com/PHACDataHub/cloudrun-deployment-example/issues/15).
      - alerting devs on slack when an error or critical level log is written in prod

If we're agreed on moving forward with providing logging configuration/helpers in this package, I'm happy to flesh out some more specific work items and help grind them out!

Probably also worth taking a step back to survey what's already out there; I know some of the structure logging libraries are relatively drop-in and bring their own configurations. Maybe there's already a library suitable for giving us a consistent logging experience, and we just need to standardize around that.

### PR DESCRIPTION
**Pull request by Stephen-ONeil**
Closes #22

TODO:
  - [x] split `logging_utils.py` in to multiple modules
  - [x] more flexible API
    - [x] remove slack hook as a default
      - brought it back as an optional part of the default helpers' logging config, but it's no longer part of the `configure_uniform_std_lib_and_structlog_logging` function
    - [x] surface access to `handlers` and `formatters` configs; some default set but consumers can override/import and configure the handlers and formatters provided by the helpers repo as needed
    - [x] what parts of the API, if any, make sense as environment variables? Maybe just options for the default?
      - ended up with five env vars for controlling the default helpers' logging config settings, but all are optional in most environments. See the README logging docs for specifics
  - [x] determine if logging requirements should be in `setup.cfg` or if they should be optional like `openpyxl`
  - [x] rework library env var pattern so that all env vars can either come from a `.env` file _or_ be declared in `settings.py` 
  - [x] docs
  - [x] expand testing scope, need to test the configuration function API itself, rather than just the behaviour and utils that were being tested previously
  - [ ] test branch in ITAP to make sure there's no surprises with the env var changes

### CODE REVIEW

**Comment by Stephen-ONeil** [comment]
I plan to write a few more tests still, just for extra solid coverage, but otherwise this is all ready for review.

Will have an impact on down-stream consumers once released, since the default logging configuration is currently part of the `from phac_aspc.django.settings import *` pattern, and will require one or two `PHAC_ASPC_...` env vars depending on a given project's environment. Either I fiddle with that pattern to make it opt-in, or we make this a managed roll-out and walk all of our devs through the new logging feature.

I was also curious, @lucbelliveau, do we have a way to deploy release candidate tagged versions of the package? Could be worth doing that before this merges, because it'd be good to do a pilot test in an Azure Cloud app before this goes wide-release. I believe it's ready, but can't test in Azure myself.

@Dhanani I've tagged you as a reviewer specifically for the small Azure logging handler component. Still think we should meet to get on the same page about logging too!

**Comment by AlexCLeduc** [comment]
I think this looks good, we'll want to be careful not to interrupt itap with this type of work when merging, the logging seems a bit fragile right now. At the very least I need to get a release out before we merge this

**Comment by Stephen-ONeil** [comment]
Agreed that it shouldn't be rushed in. I do need at least one project to test the Azure logging capability out since I don't have a playground of my own there. I'll probably revisit putting the whole thing behind an env var flag, disabled by default at least for now.

**Comment by lucbelliveau** [comment]
@Stephen-ONeil there is no way to deploy RCs to pypi at the moment - but you could try something like this:

```
 pip install git+https://github.com/PHACDataHub/django-phac_aspc-helpers.git@logging-helpers
```

**Comment by Dhanani** [comment]
@Stephen-ONeil For sure! I'm free this Thursday if you want to setup a meeting :)

**Review by AlexCLeduc — DISMISSED** [review]
We'll just have to be careful with the next ITAP deployment

**Comment by Stephen-ONeil** [comment]
Oop, that last second merge from main bumped the linter version on this branch and added a new lint error. I'll hotfix that over on main.

**Pull request merged**
